FROM node:22.13.1-bookworm-slim AS build

  WORKDIR /app

  ENV PUPPETEER_SKIP_DOWNLOAD=true

  COPY package*.json ./
  RUN npm ci

  COPY . .
  RUN npx prisma generate
  RUN npm run build

  FROM node:22.13.1-bookworm-slim AS production

  WORKDIR /app

  ENV NODE_ENV=production
  ENV PUPPETEER_SKIP_DOWNLOAD=true

  COPY package*.json ./
  RUN npm ci --omit=dev

  COPY --from=build /app/dist ./dist
  COPY --from=build /app/prisma ./prisma
  COPY --from=build /app/node_modules/.prisma ./node_modules/.prisma
  COPY --from=build /app/node_modules/@prisma ./node_modules/@prisma

  EXPOSE 3000