  FROM node:22.13.1-bookworm-slim AS build

  WORKDIR /app

  ENV NODE_ENV=development
  ENV NPM_CONFIG_PRODUCTION=false
  ENV PUPPETEER_SKIP_DOWNLOAD=true

  COPY package*.json ./
  RUN npm ci --include=dev --loglevel=info

  COPY . .
  RUN ./node_modules/.bin/prisma generate
  RUN npm run build
  RUN npm prune --omit=dev

  FROM node:22.13.1-bookworm-slim AS production

  WORKDIR /app

  ENV NODE_ENV=production
  ENV PORT=3000
  ENV PUPPETEER_SKIP_DOWNLOAD=true

  COPY --from=build /app/package*.json ./
  COPY --from=build /app/node_modules ./node_modules
  COPY --from=build /app/dist ./dist
  COPY --from=build /app/prisma ./prisma
  COPY --from=build /app/prisma.config.ts ./prisma.config.ts

  EXPOSE 3000